.github/workflows/update.yml

add update bindings workflow

---

.github/workflows/update.yml

CI: fix features list for pre-build update workflow

---

Cargo.lock
api/gfx/Cargo.toml
api/gfx/src/bitmap/bitmap.rs

fix UB in `Bitmap::get_color_of_pattern`

---

Cargo.lock
README.md
api/color/Cargo.toml
api/ctrl/Cargo.toml
api/display/Cargo.toml
api/fs/Cargo.toml
api/gfx/Cargo.toml
api/menu/Cargo.toml
api/sound/Cargo.toml
api/sys/Cargo.toml
api/system/Cargo.toml
cargo/Cargo.toml
rust-toolchain.toml
support/tool/Cargo.toml

add missed metadata, update manifests, improve readme, bump versions

Metadata improvements

---

Cargo.lock
api/gfx/Cargo.toml
api/gfx/src/bitmap/bitmap.rs
api/gfx/src/bitmap/table.rs
api/gfx/src/lib.rs
api/gfx/src/text.rs

Improved docs including [missed][link] `getDisplayBufferBitmap`.
[link]: https://devforum.play.date/t/mistake-in-c-documentation-getdisplaybufferbitmap/6722/5

Improve docs in graphics crate

---

Cargo.lock
cargo/Cargo.toml
cargo/src/cli/mod.rs
cargo/src/package/mod.rs

It causes when no asses but `[package.metadata.playdate.assets.options]` is set.

Fix cargo-playdate ignores metadata if assets cash-hit

---

Cargo.lock
api/ctrl/Cargo.toml
api/ctrl/src/buttons.rs

Remove `#[const_trait]` to build on latest nightly without incomplete `effects` feature.

Fix ctrl const

---

.github/workflows/tests.yml
Cargo.lock
cargo/Cargo.toml
cargo/tests/init/init.rs
cargo/tests/init/new.rs

Now `init` / `new` tests are behind the cfg-flag.

Split `init` tests

---

Cargo.lock
cargo/Cargo.toml
cargo/src/build/mod.rs
cargo/src/main.rs
cargo/tests/build/simple.rs

Fix #315 "No packages has been produced", caused because cargo changed artefact name format - now replaces dashes with underscores for libs too.
Related cargo PR is [rust-lang/cargo#12783][] which landed will land in Cargo 1.79 (2024-06-13) according to [CHANGELOG][].
It's definitely not a perfect solution, it's just a hot-fix. It should be refactored in the near future.
[rust-lang/cargo#12783]: https://github.com/rust-lang/cargo/pull/12783
[CHANGELOG]: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#fixed

Fix cargo-playdate error "No packages has been produced"

---

.github/workflows/tests.yml
Cargo.lock
cargo/Cargo.toml
cargo/src/assets/mod.rs
cargo/src/assets/plan.rs
support/build/Cargo.toml
support/build/src/assets/mod.rs
support/build/src/assets/plan.rs
support/build/src/assets/resolver.rs
support/build/src/assets/tests.rs

Fixes #338, that happening in #319.

Fix assets missed crate root

---

Cargo.lock
api/sys/Cargo.toml
api/sys/src/sys/allocator.rs
api/sys/src/sys/proc.rs

- Fix `abort` and `panic` to do not crash simulator process (#335)
- Improve global allocator, cache fn-ptr to OS's `realloc` (#336)

Fix `panic` & `error`, improve allocator

---

cargo/src/cli/mod.rs

I believe this fixes #352.
Tested on MacOS and Windows.

Fix test: init_args_before_cmd (win)

---

cargo/README.md

I took a stab at expanding the docs for getting started (hello world) to be explicit about some of the pre-reqs (gcc-arm, cmake, rust nightly, etc).
Related to: https://github.com/boozook/playdate/issues/90

Expand pre-req instructions in hello_world readme.

---

api/sys/Cargo.toml
api/sys/src/build.rs
api/sys/src/lib.rs
api/sys/src/sys/proc.rs

`playdate-sys`: 
- improve panic (error)

Improve abort with error, panic handler

---

Cargo.lock
api/sys/Cargo.toml
api/sys/src/build.rs
support/addr2line/Cargo.toml
support/addr2line/src/build.rs
support/bindgen-cfg/Cargo.toml
support/bindgen-cfg/src/lib.rs
support/bindgen/Cargo.toml
support/bindgen/src/gen/docs/gen.rs
support/bindgen/src/gen/mod.rs
support/bindgen/src/lib.rs

Update cargo build-script output format to new that actual from rust 1.77.
Old format is deprecated.

Update cargo build-script output format

---

Cargo.lock
Cargo.toml
cargo/Cargo.toml
cargo/src/assets/mod.rs
cargo/src/assets/plan.rs
cargo/src/main.rs
cargo/src/utils/cargo/meta_deps.rs
support/build/Cargo.toml
support/build/src/assets/plan.rs
support/build/src/assets/resolver.rs

Following #376
- fix assets-build-planner
- plan compile-kind agnostic
- improve build-plan cache, add resolved env vars
To reproduce:
1. prepare package with 
- lib
- more then one bins, including `main.rs` as auto-target
- some example(s)
1. run:
```bash
cargo build -p=cargo-playdate && \
CARGO_PLAYDATE_LOG="trace" RUST_LOG="trace" ./target/debug/cargo-playdate assets -vvv \
--target-dir=./target-dev-test \
-p=test-workspace-main-crate \
--manifest-path=${PREPARED_PACKAGE_FROM_STEP_1}/Cargo.toml \
--target=thumbv7em-none-eabihf --target=your-host-target \
-- --examples --bins --lib # or --all-targets
```

Fix assets planning should be compile-kind agnostic

---

Cargo.lock
cargo/Cargo.toml
cargo/src/build/mod.rs
cargo/src/layout/cargo.rs
cargo/src/main.rs
cargo/src/package/mod.rs
cargo/src/proc/reader.rs
cargo/src/utils/cargo/format.rs
cargo/src/utils/cargo/meta_deps.rs
cargo/src/utils/cargo/unit_graph.rs
cargo/src/utils/workspace.rs

- now doesn't corrupting cargo's caches, partially fixes #177
- supports auto-targets

Build without cargo's build-plan and build-ctx, just unit-tree

---

Cargo.lock
support/addr2line/Cargo.toml
support/addr2line/src/addr2line-crashlog.rs
support/addr2line/src/ef.rs
support/addr2line/src/fmt/crashlog.rs
support/addr2line/src/lib.rs

New human-readable output format:
```text
Crash at 2024/06/22 05:10:05
BUILD:   216ce27b-2.5.0-release.169289-buildbot
HEAP:    78912
General-purpose registers (stack)
0:       0x240f0074: ??
1:       0x0133d8: ??
2:       0x000000: ??
3:       0x90001335: ??
12:      0x000001:
selfrel_offset31 (0x1 - 0x13)
14 LR:   0x240534d5:
pd_loadPDX (0x2405323c - 0x2405374c) [hw:1]
at playdate.c:1034 (0x2405323c - ??) [hw:604320316]
?? (0x240534d5 - ??)
at playdate.c:1213 (0x240534d2 - ??) [hw:1]
at playdate.c:1215 (0x240534d4 - ??) [hw:1]
15 PC:   0x6000d5e8:
__rust_alloc (0xd5d4 - 0xd5fc)
at allocator.rs:23 (0xd5e6 - 0xd5f2)
Special registers
MMFAR:   0x0133d8: ??
BFAR:    0x0133d8: ??
rcccsr:  0x000000: ??
CFSR:     0b000000000000000000000010000010 (Configurable Fault Status)
MMFSR: …
```

Fix crashlog-symbolizer register decoder

---

Cargo.lock
api/sys/Cargo.toml
api/sys/README.md
cargo/tests/crates/simple/with-cfg/.cargo/config.toml
support/utils/Cargo.toml
support/utils/src/compile.rs

@boozook here you go. I don't have this set up locally so can't test it, but I think this is the right set of changes.

Add needed RUSTFLAGS for supporting Rev A hardware

---

README.md

This pull request covers some minor improvements to the README. These consist of:
* Fixing the `playdate-sound` example to use the actual example name, `sp`, instead of the source file name, `sp-simple`
* Add the required feature flag to all example commands. When I first ran these locally, compilation failed due to the required features not being met.

Minor Improvements to the README

---

Cargo.lock
api/sys/Cargo.toml
api/sys/src/lib.rs
rust-toolchain.toml

- remove feature `panic_info_message` that has been stable since 1.81.0
- update toolchain
- improve `from_residual` in `sys`

Various minor updates

---

rust-toolchain.toml

` nightly-2025-03-17` -> ` nightly-2025-03-21`

Update rust toolchain to ` nightly-2025-03-17`

---

rust-toolchain.toml

`nightly-2025-03-21` -> `nightly-2025-03-28`

Update rust toolchain to `nightly-2025-03-28`

---

rust-toolchain.toml

`nightly-2025-03-28` -> `nightly-2025-04-04`

Update rust toolchain to `nightly-2025-04-04`

---

rust-toolchain.toml

` nightly-2025-04-09` -> ` nightly-2025-04-11`

Update rust toolchain to ` nightly-2025-04-09`
