- .github/workflows/cleanup-caches.yml
- .github/workflows/tests.yml
- Cargo.lock
- cargo/tests/build/simple.rs
- cargo/tests/common.rs
- cargo/tests/crates/metadata/bin.rs
- cargo/tests/crates/workspace/bin.rs
- cargo/tests/run/simple.rs
- speed up the tools test process by using a shared build folder
- fix cache for tests
- add cache cleanup workflow
> CI: speed up tests

- .github/workflows/publish.yml
- Cargo.lock
- Cargo.toml
- api/display/Cargo.toml
- api/display/src/lib.rs
- api/gfx/Cargo.toml
- api/gfx/src/api.rs
- api/gfx/src/bitmap/api.rs
- api/gfx/src/bitmap/bitmap.rs
- api/gfx/src/bitmap/table.rs
- api/gfx/src/error.rs
- api/gfx/src/lib.rs
- api/gfx/src/text.rs
- api/gfx/src/video.rs
- api/playdate/Cargo.toml
- api/playdate/examples/video.rs
- api/playdate/src/lib.rs
- api/sprite/Cargo.toml
- api/sprite/src/lib.rs
- api/system/Cargo.toml
- api/system/src/lib.rs
Also title gfx refactoring needed for the subject.
> Add cached api end points (part 1)

- Cargo.lock
- Cargo.toml
- api/playdate/Cargo.toml
- api/playdate/examples/hello-world.rs
- api/playdate/examples/video.rs
- api/sound/Cargo.toml
- api/sound/README.md
- api/sound/examples/README.md
- api/sound/examples/sp-simple.rs
- api/sound/src/player/fp/mod.rs
- api/sound/src/player/sp/mod.rs
- api/sound/src/sample.rs
- api/sys/Cargo.toml
- api/sys/examples/handler.rs
- api/sys/src/lib.rs
- api/system/Cargo.toml
- api/system/examples/handler-boxed.rs
- api/system/examples/handler-pinned.rs
- api/system/examples/handler-static.rs
- api/system/src/lib.rs
- api/system/src/update.rs
- cargo/Cargo.toml
- cargo/src/init/bin-hl.rs
- cargo/src/init/lib-hl.rs
Also fix examples and templates.
> Better ctrl-flow

- .github/workflows/publish.yml
- Cargo.lock
- api/gfx/Cargo.toml
- api/gfx/src/api.rs
- api/gfx/src/text.rs
- api/playdate/Cargo.toml
- api/sprite/Cargo.toml
- api/sprite/src/api.rs
- api/sprite/src/sprite.rs
- api/sys/Cargo.toml
- api/sys/gen/pd2.1.0-beta.1-gen0.1-debug-aarch64-apple-darwin-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-debug-aarch64-apple-darwin-111111110.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-debug-thumbv7em-none-eabihf-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-debug-thumbv7em-none-eabihf-111111110.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-release-aarch64-apple-darwin-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-release-aarch64-apple-darwin-111111110.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-release-thumbv7em-none-eabihf-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-gen0.1-release-thumbv7em-none-eabihf-111111110.rs
[dev-forum](https://devforum.play.date/t/check-out-playdate-os-sdk-2-1-0-beta-1/13417)
> Add SDK v2.1 compatibility

- Cargo.lock
- Cargo.toml
- api/ctrl/Cargo.toml
- api/ctrl/examples/accelerometer.rs
- api/ctrl/examples/buttons.rs
- api/ctrl/src/api.rs
- api/ctrl/src/lib.rs
- api/ctrl/src/peripherals.rs
- api/display/Cargo.toml
- api/display/src/lib.rs
- api/gfx/Cargo.toml
- api/playdate/Cargo.toml
- api/playdate/src/lib.rs
- api/sprite/Cargo.toml
- api/system/Cargo.toml
- api/system/examples/handler-boxed.rs
- api/system/examples/handler-pinned.rs
- api/system/examples/handler-static.rs
- api/system/src/lib.rs
- improve ctrls api
- fix examples, docs, metadata.
> Improve controls api

- Cargo.lock
- cargo/Cargo.toml
- cargo/src/cli/ide.rs
- cargo/src/cli/mod.rs
- cargo/src/cli/opts.rs
- cargo/src/config.rs
- cargo/src/init/ide/vsc/extensions.json
- cargo/src/init/lib-hl.rs
- cargo/src/init/mod.rs
- add basic ide-template for `init`/`new`
- improve generated metadata
(closes #149)
> Add basic ide-template for `init`/`new`

- Cargo.lock
- api/display/Cargo.toml
- api/display/src/lib.rs
- api/gfx/Cargo.toml
- api/gfx/examples/font.rs
- api/gfx/src/bitmap/api.rs
- api/gfx/src/bitmap/bitmap.rs
- api/gfx/src/bitmap/table.rs
- api/gfx/src/text.rs
- api/playdate/Cargo.toml
- api/playdate/examples/hello-world.rs
- api/sprite/Cargo.toml
- api/sprite/src/callback/collision.rs
- api/sprite/src/callback/draw.rs
- api/sprite/src/callback/update.rs
- api/sprite/src/sprite.rs
- api/sys/Cargo.toml
- api/sys/src/sys/panic.rs
- api/system/Cargo.toml
- api/system/src/lib.rs
* gfx: one endpoint instead many, remove unnecessary results
* sprite: pub mods, fix docs
* system: add `current_time_milliseconds_raw`
* display: `DisplayScale` const cast methods
> Api various  improvements

- .github/FUNDING.yml
- .github/workflows/tests.yml
- .github/workflows/update.yml
- api/sys/gen/pd2.1.0-beta.1-p64-i32-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-p64-i32-111111110.rs
- api/sys/gen/pd2.1.0-beta.1-pd-000100000.rs
- api/sys/gen/pd2.1.0-beta.1-pd-111111110.rs
> CI: fix update workflow, update fundings

- Cargo.lock
- Cargo.toml
- README.md
- api/sys/Cargo.toml
- components/crank-indicator/Cargo.toml
- components/crank-indicator/README.md
- components/crank-indicator/examples/README.md
- components/crank-indicator/examples/example.rs
- components/crank-indicator/src/lib.rs
> Add crank-indicator ui component

- .github/workflows/tests.yml
windows tests is temporarily disabled.
> Update min SDK version for tests

- support/utils/src/toolchain/sdk.rs
Report success via `cargo::info` if playdate SDK was found.
> Report success if SDK has been found

- Cargo.lock
- support/utils/Cargo.toml
- support/utils/src/toolchain/sdk.rs
Check Windows registry for SDK path
> Check Windows registry for SDK path

- .github/actions/tools-deps/action.yml
- .github/workflows/dev-build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .github/workflows/update.yml
- added reusable action for deps, 
- enabled tests on windows almost everywhere.
> Tests on windows + action for dependencies

- .github/workflows/dev-build.yml
- Cargo.lock
- cargo/Cargo.toml
- support/device/Cargo.toml
- support/device/src/mount/linux.rs
- support/device/src/mount/mac.rs
- support/device/src/mount/win.rs
- support/tool/Cargo.toml
- support/tool/README.md
- support/tool/src/cli.rs
- support/tool/src/main.rs
Improved device unmounting on linux & windows.
> Improve device unmounting

- cargo/README.md
- cargo/src/main.rs
I spotted a couple of things that I thought should be worded slightly differently.
Thanks for all of your hard work on this project!
> Minor grammar fixes

- api/system/src/event.rs
> Fix some doc aliases

- Cargo.lock
- api/system/Cargo.toml
- cargo/Cargo.toml
> Bump changed crates

- .github/workflows/tests.yml
- Cargo.lock
- codemagic.yaml
- support/build/Cargo.toml
- support/build/src/assets/mod.rs
- support/build/src/io.rs
> Package examples on windows

- Cargo.lock
- api/ctrl/Cargo.toml
- api/menu/Cargo.toml
- api/playdate/Cargo.toml
- api/sprite/Cargo.toml
- components/crank-indicator/Cargo.toml
Fixes missed update after minor versions of other was incremented.
> Bump crates

- api/sys/Cargo.toml
- api/sys/gen/pd2.6.0-beta.2-linux-x86_64-64-i32-000100000.rs
- api/sys/gen/pd2.6.0-beta.2-linux-x86_64-64-i32-111111110.rs
- api/sys/gen/pd2.6.0-beta.2-pd-000100000.rs
- api/sys/gen/pd2.6.0-beta.2-pd-111111110.rs
- api/sys/gen/pd2.6.0-beta.2-windows-aarch64-64-i32-000100000.rs
- api/sys/gen/pd2.6.0-beta.2-windows-aarch64-64-i32-111111110.rs
- api/sys/gen/pd2.6.0-beta.2-windows-x86_64-64-i32-000100000.rs
- api/sys/gen/pd2.6.0-beta.2-windows-x86_64-64-i32-111111110.rs
- api/sys/gen/pd2.7.0-beta.2-macos-aarch64-64-i32-111111110.rs
- api/sys/gen/pd2.7.0-beta.2-macos-x86_64-64-i32-111111110.rs
> Update pre-built bindings

- Cargo.lock
- support/addr2line/Cargo.toml
- support/addr2line/README.md
[Rendered README](https://github.com/boozook/playdate/blob/doc/playdate-symbolize-improve/support/addr2line/README.md)
> Improve `playdate-symbolize` doc

- rust-toolchain.toml
` nightly-2025-04-04` -> ` nightly-2025-04-07`
> Update rust toolchain to ` nightly-2025-04-04`
